services:
  db:
    image: postgres:17
  web:
    environment:
      OPENPROJECT_DISABLE__PASSWORD__LOGIN: "false"
      OPENPROJECT_OMNIAUTH__DIRECT__LOGIN__PROVIDER: ""

  worker:
    environment:
      OPENPROJECT_DISABLE__PASSWORD__LOGIN: "false"
      OPENPROJECT_OMNIAUTH__DIRECT__LOGIN__PROVIDER: ""

  cron:
    environment:
      OPENPROJECT_DISABLE__PASSWORD__LOGIN: "false"
      OPENPROJECT_OMNIAUTH__DIRECT__LOGIN__PROVIDER: ""

  seeder:
    environment:
      OPENPROJECT_DISABLE__PASSWORD__LOGIN: "false"
      OPENPROJECT_OMNIAUTH__DIRECT__LOGIN__PROVIDER: ""
